# Generated by Django 4.2.28 on 2026-07-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0002_county'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='counties', to='atlas_app.language'),
        ),
    ]
