# Generated by Django 4.2.28 on 2026-07-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlas_app', '0003_county_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='county',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='county',
            name='language_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='county',
            name='tribes',
            field=models.TextField(blank=True),
        ),
    ]
