from django.core.management.base import BaseCommand

from atlas_app.models import County, Language, Region


class Command(BaseCommand):
    help = 'Seed the Kenya atlas prototype with county-level cultural and linguistic data'

    def handle(self, *args, **options):
        County.objects.all().delete()
        Region.objects.all().delete()
        Language.objects.all().delete()

        regions = [
            {'name': 'Nairobi', 'description': 'Capital region with urban diversity.', 'population': 4500000, 'languages': 'Swahili, English, Kikuyu'},
            {'name': 'Coast', 'description': 'Kenya’s coastal belt with rich Swahili and Mijikenda heritage.', 'population': 4200000, 'languages': 'Swahili, Mijikenda, English'},
            {'name': 'North Eastern', 'description': 'A region shaped by Somali and Cushitic traditions.', 'population': 2600000, 'languages': 'Somali, Swahili, English'},
            {'name': 'Eastern', 'description': 'A region with strong pastoral and farming traditions.', 'population': 6200000, 'languages': 'Kamba, Meru, Swahili'},
            {'name': 'Central', 'description': 'Known for Kikuyu heritage and highland farming.', 'population': 5000000, 'languages': 'Kikuyu, English, Swahili'},
            {'name': 'Rift Valley', 'description': 'Home to many pastoral communities and vibrant cultural traditions.', 'population': 11000000, 'languages': 'Kalenjin, Maasai, Swahili'},
            {'name': 'Western', 'description': 'A region of lush highlands and great linguistic diversity.', 'population': 4700000, 'languages': 'Luhya, Swahili, English'},
            {'name': 'Nyanza', 'description': 'Home to Luo and Kisii communities and Lake Victoria traditions.', 'population': 6200000, 'languages': 'Luo, Kisii, Swahili'},
        ]

        created_regions = {}
        for region in regions:
            created_regions[region['name']] = Region.objects.create(**region)

        language_names = [
            'Swahili', 'English', 'Kikuyu', 'Luo', 'Kalenjin', 'Maasai', 'Kisii', 'Luhya', 'Somali',
            'Mijikenda', 'Kamba', 'Meru', 'Turkana', 'Pokot', 'Aembu', 'Mbeere', 'Orma'
        ]
        languages = {}
        for name in language_names:
            languages[name] = Language.objects.create(
                name=name,
                family='Bantu' if name in {'Swahili', 'Kikuyu', 'Kisii', 'Luhya', 'Kamba', 'Meru', 'Mijikenda'} else 'Nilotic' if name in {'Luo', 'Kalenjin', 'Maasai', 'Turkana', 'Pokot', 'Orma'} else 'Cushitic' if name == 'Somali' else 'Germanic',
                speakers='Wide' if name in {'Swahili', 'English'} else 'Regional',
                description=f'{name} is an important language across Kenya.',
            )

        county_profiles = [
            {'name': 'Nairobi County', 'region': 'Nairobi', 'population': 4397073, 'image_url': 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1200&q=80', 'history': "Nairobi grew from a colonial railway town into Kenya's political and economic heart. Its neighborhoods reflect waves of migration from across the country.", 'tribes': 'Kikuyu, Luhya, Luo, Kalenjin and many other communities live in Nairobi, creating a city of many cultural identities.', 'language_details': 'Swahili is the everyday lingua franca, English dominates official and professional spaces, and Kikuyu remains strongly rooted in the city\'s social life.', 'languages': ['Swahili', 'English', 'Kikuyu']},
            {'name': 'Kisumu County', 'region': 'Nyanza', 'population': 968909, 'image_url': 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80', 'history': 'Kisumu rose as a key port on Lake Victoria and remains culturally tied to the lake and its trade networks.', 'tribes': 'The Luo community is the most prominent, with Kisii and other communities also contributing to the region\'s traditions.', 'language_details': 'Luo is a key cultural language in Kisumu, while Swahili and English are used widely for trade, education, and administration.', 'languages': ['Swahili', 'English', 'Luo']},
            {'name': 'Mombasa County', 'region': 'Coast', 'population': 1200000, 'image_url': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', 'history': 'Mombasa developed as a major Indian Ocean port and remains a gateway for trade and culture.', 'tribes': 'The Mijikenda and Swahili communities are especially prominent in the county\'s heritage.', 'language_details': 'Swahili is the main everyday language, while English is used in official spaces and Arabic influences remain visible in the coastal culture.', 'languages': ['Swahili', 'English', 'Mijikenda']},
            {'name': 'Kwale County', 'region': 'Coast', 'population': 866820, 'image_url': 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80', 'history': 'Kwale is known for its long coastline, cultural festivals, and the deep-rooted traditions of the Mijikenda.', 'tribes': 'Mijikenda communities form the backbone of Kwale\'s cultural identity.', 'language_details': 'Swahili and Mijikenda languages are central to daily life, with English used in schooling and administration.', 'languages': ['Swahili', 'Mijikenda', 'English']},
            {'name': 'Kilifi County', 'region': 'Coast', 'population': 1450000, 'image_url': 'https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1200&q=80', 'history': 'Kilifi reflects a blend of coastal trade, Islamic influence, and rural farming life.', 'tribes': 'The Mijikenda and Swahili communities shape the county\'s identity.', 'language_details': 'Swahili is widely spoken alongside Mijikenda languages and English in formal settings.', 'languages': ['Swahili', 'Mijikenda', 'English']},
            {'name': 'Tana River County', 'region': 'Coast', 'population': 315000, 'image_url': 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80', 'history': 'Tana River has long been linked to riverine trade, fishing, and pastoral movements.', 'tribes': 'The Pokomo and Orma communities are central to the county\'s social life.', 'language_details': 'Swahili connects people across the county, while local languages remain strong in family and community life.', 'languages': ['Swahili', 'Orma', 'Pokot']},
            {'name': 'Lamu County', 'region': 'Coast', 'population': 143000, 'image_url': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', 'history': 'Lamu is one of Kenya\'s oldest Swahili settlements, famous for its architecture and maritime heritage.', 'tribes': 'Swahili and Mijikenda traditions are especially visible in Lamu\'s urban and rural life.', 'language_details': 'Swahili is the main language of communication, with Arabic and English also playing important roles.', 'languages': ['Swahili', 'English', 'Mijikenda']},
            {'name': 'Taita Taveta County', 'region': 'Coast', 'population': 340000, 'image_url': 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80', 'history': 'The county combines highland landscapes, trade routes, and a strong sense of local identity.', 'tribes': 'The Taita and Taveta peoples are central to the county\'s culture.', 'language_details': 'Taita and Taveta languages remain significant alongside Swahili and English.', 'languages': ['Swahili', 'English', 'Mijikenda']},
            {'name': 'Garissa County', 'region': 'North Eastern', 'population': 841000, 'image_url': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', 'history': 'Garissa grew as a key centre for trade and governance in the north-eastern frontier.', 'tribes': 'Somali communities form the majority of the county\'s population.', 'language_details': 'Somali is the dominant language, with Swahili and English used in education and public affairs.', 'languages': ['Somali', 'Swahili', 'English']},
            {'name': 'Wajir County', 'region': 'North Eastern', 'population': 781000, 'image_url': 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=1200&q=80', 'history': 'Wajir is shaped by pastoral life, clan ties, and a strong culture of mobility.', 'tribes': 'Somali clans and sub-clans define much of the county\'s social structure.', 'language_details': 'Somali is the main language of everyday life, with Swahili and English used more formally.', 'languages': ['Somali', 'Swahili', 'English']},
            {'name': 'Mandera County', 'region': 'North Eastern', 'population': 867000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Mandera has long been tied to cross-border trade and nomadic movement.', 'tribes': 'Somali communities and clan-based social networks are central to the county.', 'language_details': 'Somali remains the main language of expression, while Swahili and English are increasingly used in public life.', 'languages': ['Somali', 'Swahili', 'English']},
            {'name': 'Marsabit County', 'region': 'Eastern', 'population': 459000, 'image_url': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', 'history': 'Marsabit sits at the meeting point of pastoral traditions, mountain culture, and border trade.', 'tribes': 'The Borana, Gabra, and Rendille communities are especially prominent.', 'language_details': 'Local Cushitic languages are strong in everyday life, alongside Swahili and English.', 'languages': ['Somali', 'Swahili', 'English']},
            {'name': 'Isiolo County', 'region': 'Eastern', 'population': 268000, 'image_url': 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1200&q=80', 'history': 'Isiolo is known for its role as a meeting point for traders and pastoralists.', 'tribes': 'The Borana and Samburu communities shape much of the county\'s cultural landscape.', 'language_details': 'Several local languages thrive alongside Swahili and English.', 'languages': ['Swahili', 'English', 'Somali']},
            {'name': 'Meru County', 'region': 'Eastern', 'population': 1540000, 'image_url': 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80', 'history': 'Meru is known for fertile highlands, agriculture, and long-standing community institutions.', 'tribes': 'The Meru community is the core cultural group, with other communities also contributing to local life.', 'language_details': 'Meru is an important vernacular language, while Swahili and English are used more formally.', 'languages': ['Meru', 'Swahili', 'English']},
            {'name': 'Tharaka-Nithi County', 'region': 'Eastern', 'population': 393000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'The county carries a strong history of farming, kinship networks, and local leadership.', 'tribes': 'The Tharaka and Mwimbi communities give the county a distinct social character.', 'language_details': 'Local languages remain important alongside Swahili and English.', 'languages': ['Meru', 'Swahili', 'English']},
            {'name': 'Embu County', 'region': 'Eastern', 'population': 600000, 'image_url': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', 'history': 'Embu is shaped by its rolling highlands, farming traditions, and strong community values.', 'tribes': 'The Embu people are the main cultural group in the county.', 'language_details': 'Embu is a key spoken language, while Swahili and English support wider communication.', 'languages': ['Kamba', 'Swahili', 'English']},
            {'name': 'Kitui County', 'region': 'Eastern', 'population': 1130000, 'image_url': 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1200&q=80', 'history': 'Kitui carries a history rooted in trade, dryland farming, and resilient community networks.', 'tribes': 'The Kamba people are central to the county\'s identity.', 'language_details': 'Kamba is widely spoken, with Swahili and English used in public and formal settings.', 'languages': ['Kamba', 'Swahili', 'English']},
            {'name': 'Machakos County', 'region': 'Eastern', 'population': 1160000, 'image_url': 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80', 'history': 'Machakos has long been known for its market networks, migration stories, and strong local leadership.', 'tribes': 'The Kamba people and other communities contribute to the county\'s social diversity.', 'language_details': 'Kamba remains important, while Swahili and English are widely understood.', 'languages': ['Kamba', 'Swahili', 'English']},
            {'name': 'Makueni County', 'region': 'Eastern', 'population': 987000, 'image_url': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', 'history': 'Makueni reflects the story of dryland adaptation, farming, and community resourcefulness.', 'tribes': 'The Kamba community dominates the county\'s cultural life.', 'language_details': 'Kamba is central to everyday life, with Swahili and English used in schools and administration.', 'languages': ['Kamba', 'Swahili', 'English']},
            {'name': 'Nyandarua County', 'region': 'Central', 'population': 638000, 'image_url': 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80', 'history': 'Nyandarua is known for its highland landscapes and strong agricultural history.', 'tribes': 'Kikuyu communities form the majority of the county\'s cultural life.', 'language_details': 'Kikuyu is widely spoken, with English and Swahili supporting formal communication.', 'languages': ['Kikuyu', 'Swahili', 'English']},
            {'name': 'Nyeri County', 'region': 'Central', 'population': 759000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Nyeri carries deep agricultural traditions and a strong heritage of community leadership.', 'tribes': 'The Kikuyu community is central to the county\'s identity.', 'language_details': 'Kikuyu remains the most familiar vernacular, while Swahili and English are used more widely in education.', 'languages': ['Kikuyu', 'Swahili', 'English']},
            {'name': 'Kirinyaga County', 'region': 'Central', 'population': 610000, 'image_url': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', 'history': 'Kirinyaga is known for its lush farms and long-standing Kikuyu traditions.', 'tribes': 'Kikuyu communities shape the county\'s cultural and social life.', 'language_details': 'Kikuyu is widely spoken alongside Swahili and English.', 'languages': ['Kikuyu', 'Swahili', 'English']},
            {'name': 'Murang\'a County', 'region': 'Central', 'population': 1050000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Murang\'a is one of the most culturally significant counties in central Kenya, with strong homegrown traditions.', 'tribes': 'The Kikuyu community is deeply rooted in the county\'s identity.', 'language_details': 'Kikuyu is a dominant language, with Swahili and English supporting formal and urban communication.', 'languages': ['Kikuyu', 'Swahili', 'English']},
            {'name': 'Kiambu County', 'region': 'Central', 'population': 2500000, 'image_url': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', 'history': 'Kiambu combines urban growth with deep agricultural traditions and rich Kikuyu heritage.', 'tribes': 'Kikuyu communities and migrant groups make up the county\'s diverse social fabric.', 'language_details': 'Kikuyu is widely spoken, while Swahili and English are common in commerce and education.', 'languages': ['Kikuyu', 'Swahili', 'English']},
            {'name': 'Turkana County', 'region': 'Rift Valley', 'population': 926000, 'image_url': 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80', 'history': 'Turkana is shaped by arid landscapes, pastoral life, and strong clan networks.', 'tribes': 'The Turkana people are central to the county\'s culture.', 'language_details': 'Turkana is a major spoken language, and Swahili is used widely for trade and administration.', 'languages': ['Turkana', 'Swahili', 'English']},
            {'name': 'West Pokot County', 'region': 'Rift Valley', 'population': 621000, 'image_url': 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1200&q=80', 'history': 'West Pokot reflects the resilience of pastoral communities living in rugged terrain.', 'tribes': 'The Pokot people are the main cultural group in the county.', 'language_details': 'Pokot remains a strong local language, while Swahili and English support wider communication.', 'languages': ['Pokot', 'Swahili', 'English']},
            {'name': 'Samburu County', 'region': 'Rift Valley', 'population': 310000, 'image_url': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', 'history': 'Samburu is known for its pastoral traditions, strong clan identity, and cultural ceremonies.', 'tribes': 'The Samburu people dominate the county\'s cultural life.', 'language_details': 'Samburu languages are important locally, while Swahili and English are used in trade and schooling.', 'languages': ['Swahili', 'English', 'Maasai']},
            {'name': 'Trans Nzoia County', 'region': 'Rift Valley', 'population': 990000, 'image_url': 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80', 'history': 'Trans Nzoia grew from farming settlements into a major agricultural region.', 'tribes': 'The Luhya, Kalenjin, and other communities contribute to the county\'s diversity.', 'language_details': 'Swahili and English are widely used, with local languages staying strong in homes and markets.', 'languages': ['Luhya', 'Swahili', 'English']},
            {'name': 'Uasin Gishu County', 'region': 'Rift Valley', 'population': 1160000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Uasin Gishu is known for its farming economy and strong educational institutions.', 'tribes': 'Kalenjin communities are prominent, alongside others from across the country.', 'language_details': 'Kalenjin languages are important locally, with Swahili and English used widely in school and work.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Elgeyo-Marakwet County', 'region': 'Rift Valley', 'population': 454000, 'image_url': 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80', 'history': 'Elgeyo-Marakwet carries a strong heritage of hilltop settlements and cultural endurance.', 'tribes': 'The Elgeyo and Marakwet communities shape the county\'s identity.', 'language_details': 'Kalenjin languages are central, with Swahili and English used in wider communication.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Nandi County', 'region': 'Rift Valley', 'population': 889000, 'image_url': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', 'history': 'Nandi is known for its strong pastoral history, resilience, and cultural ceremonies.', 'tribes': 'Nandi communities are central to the county\'s cultural life.', 'language_details': 'Kalenjin languages remain strong in family life, while Swahili and English are widely used in administration and education.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Baringo County', 'region': 'Rift Valley', 'population': 666000, 'image_url': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', 'history': 'Baringo combines highland life, lake ecology, and deep pastoral traditions.', 'tribes': 'The Tugen, Pokot, and Njemps communities shape the county\'s diversity.', 'language_details': 'Local languages and Swahili are both central to communication in the county.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Laikipia County', 'region': 'Rift Valley', 'population': 518000, 'image_url': 'https://images.unsplash.com/photo-1500375592092-40eb2168fd21?auto=format&fit=crop&w=1200&q=80', 'history': 'Laikipia carries a history of ranching, conservation, and intercommunal living.', 'tribes': 'The Maasai and Kikuyu communities are significant in the county\'s social landscape.', 'language_details': 'Maasai and Kikuyu languages remain meaningful alongside Swahili and English.', 'languages': ['Maasai', 'Kikuyu', 'English']},
            {'name': 'Nakuru County', 'region': 'Rift Valley', 'population': 2200000, 'image_url': 'https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=1200&q=80', 'history': 'Nakuru grew from a colonial town into one of Kenya\'s most dynamic urban and agricultural centres.', 'tribes': 'Kalenjin, Kikuyu, and other communities shape the county\'s diversity.', 'language_details': 'Swahili and English are widely used, while local languages remain strong in homes and markets.', 'languages': ['Kikuyu', 'Kalenjin', 'Swahili']},
            {'name': 'Narok County', 'region': 'Rift Valley', 'population': 1150000, 'image_url': 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?auto=format&fit=crop&w=1200&q=80', 'history': 'Narok is known for its wide plains, Maasai heritage, and cultural festivals.', 'tribes': 'The Maasai people are the clearest cultural symbol of the county.', 'language_details': 'Maasai remains a very important language, alongside Swahili and English.', 'languages': ['Maasai', 'Swahili', 'English']},
            {'name': 'Kajiado County', 'region': 'Rift Valley', 'population': 1110000, 'image_url': 'https://images.unsplash.com/photo-1493558103817-58b2924bce98?auto=format&fit=crop&w=1200&q=80', 'history': 'Kajiado combines pastoral traditions with rapid urban and peri-urban growth.', 'tribes': 'The Maasai community is central to the county\'s identity.', 'language_details': 'Maasai remains important locally, while Swahili and English are used increasingly in education and business.', 'languages': ['Maasai', 'Swahili', 'English']},
            {'name': 'Kericho County', 'region': 'Rift Valley', 'population': 901000, 'image_url': 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80', 'history': 'Kericho is known for tea estates and a strong Kalenjin cultural history.', 'tribes': 'Kalenjin communities form the core of the county\'s identity.', 'language_details': 'Kalenjin languages remain strong, while Swahili and English are used more widely in public life.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Bomet County', 'region': 'Rift Valley', 'population': 875000, 'image_url': 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?auto=format&fit=crop&w=1200&q=80', 'history': 'Bomet is shaped by agricultural life, cultural festivals, and deep Kalenjin traditions.', 'tribes': 'The Kalenjin people are the dominant cultural group in the county.', 'language_details': 'Kalenjin is significant in homes and public life, while Swahili and English are present in schools and offices.', 'languages': ['Kalenjin', 'Swahili', 'English']},
            {'name': 'Kakamega County', 'region': 'Western', 'population': 1860000, 'image_url': 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=1200&q=80', 'history': 'Kakamega carries a history of farming, trade and strong Luhya cultural life.', 'tribes': 'The Luhya community is the most prominent in the county.', 'language_details': 'Luhya languages are important locally, while Swahili and English are used in wider communication.', 'languages': ['Luhya', 'Swahili', 'English']},
            {'name': 'Vihiga County', 'region': 'Western', 'population': 590000, 'image_url': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', 'history': 'Vihiga is known for its fertile lands and strong community traditions.', 'tribes': 'The Luhya people are central to the county\'s identity.', 'language_details': 'Luhya languages remain central, with Swahili and English used widely in education.', 'languages': ['Luhya', 'Swahili', 'English']},
            {'name': 'Bungoma County', 'region': 'Western', 'population': 1700000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Bungoma has a rich history of agriculture, trade, and Luhya cultural traditions.', 'tribes': 'The Luhya community dominates the county\'s cultural life.', 'language_details': 'Luhya is prominent in everyday speech, while Swahili and English are used in administration and schooling.', 'languages': ['Luhya', 'Swahili', 'English']},
            {'name': 'Busia County', 'region': 'Western', 'population': 893000, 'image_url': 'https://images.unsplash.com/photo-1500534623283-312aade485b7?auto=format&fit=crop&w=1200&q=80', 'history': 'Busia connects Kenya to the wider Lake Victoria region and carries strong cross-border cultural ties.', 'tribes': 'The Luhya and other communities contribute to the county\'s social diversity.', 'language_details': 'Luhya is important locally, while Swahili and English are widely understood.', 'languages': ['Luhya', 'Swahili', 'English']},
            {'name': 'Siaya County', 'region': 'Nyanza', 'population': 993000, 'image_url': 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80', 'history': 'Siaya is rooted in Lake Victoria life, fishing traditions, and Luo heritage.', 'tribes': 'The Luo community is the main cultural group in the county.', 'language_details': 'Luo is important in homes and ceremonies, while Swahili and English are common in schools and markets.', 'languages': ['Luo', 'Swahili', 'English']},
            {'name': 'Homa Bay County', 'region': 'Nyanza', 'population': 1100000, 'image_url': 'https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?auto=format&fit=crop&w=1200&q=80', 'history': 'Homa Bay is strongly linked to Lake Victoria, fishing livelihoods, and Luo traditions.', 'tribes': 'The Luo community is the dominant cultural identity in the county.', 'language_details': 'Luo is widely spoken, with Swahili and English used for business and education.', 'languages': ['Luo', 'Swahili', 'English']},
            {'name': 'Migori County', 'region': 'Nyanza', 'population': 1120000, 'image_url': 'https://images.unsplash.com/photo-1493246507139-91e8fad9978e?auto=format&fit=crop&w=1200&q=80', 'history': 'Migori carries a strong story of agricultural growth, migration, and Lake Victoria culture.', 'tribes': 'The Luo and Kuria communities are especially significant here.', 'language_details': 'Luo is important locally, while Swahili and English support wider communication.', 'languages': ['Luo', 'Swahili', 'English']},
            {'name': 'Kisii County', 'region': 'Nyanza', 'population': 1260000, 'image_url': 'https://images.unsplash.com/photo-1521295121783-8a321d551ad2?auto=format&fit=crop&w=1200&q=80', 'history': 'Kisii is known for its highland farming traditions and active community networks.', 'tribes': 'The Kisii people form the backbone of the county\'s cultural identity.', 'language_details': 'Kisii is widely spoken, with Swahili and English used in schooling and commerce.', 'languages': ['Kisii', 'Swahili', 'English']},
            {'name': 'Nyamira County', 'region': 'Nyanza', 'population': 605000, 'image_url': 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=1200&q=80', 'history': 'Nyamira blends highland farming traditions with a strong Kisii cultural heritage.', 'tribes': 'The Kisii community is the main cultural force in the county.', 'language_details': 'Kisii remains important in everyday life, with Swahili and English used more formally.', 'languages': ['Kisii', 'Swahili', 'English']},
        ]

        for profile in county_profiles:
            county = County.objects.create(
                region=created_regions[profile['region']],
                name=profile['name'],
                population=profile['population'],
                image_url=profile['image_url'],
                history=profile['history'],
                tribes=profile['tribes'],
                language_details=profile['language_details'],
            )
            county.languages.set([languages[name] for name in profile['languages'] if name in languages])

        self.stdout.write(self.style.SUCCESS('Seeded Kenya county atlas data for the full map'))
